attr_noise_scale: 300
adj_noise_scale: 300

alpha: 0.01
pre_n_samples: 10
n_samples: 1000

certify: False

classifier: 'gcn'
classifier_nlayers: 1
classifier_path: 'gnn_checkpoints/gcn_citeseer_l1.pt'