wandb_version: 1

meta_data/variant:
  desc: null
  value: GraphJointDiffuser
gnn_X/hidden_t:
  desc: null
  value: 32
gnn_X/hidden_X:
  desc: null
  value: 512
gnn_X/hidden_Y:
  desc: null
  value: 64
gnn_X/num_gnn_layers:
  desc: null
  value: 2
gnn_X/dropout:
  desc: null
  value: 0.0
gnn_E/hidden_t:
  desc: null
  value: 32
gnn_E/hidden_X:
  desc: null
  value: 512
gnn_E/hidden_Y:
  desc: null
  value: 64
gnn_E/hidden_E:
  desc: null
  value: 128
gnn_E/num_gnn_layers:
  desc: null
  value: 2
gnn_E/dropout:
  desc: null
  value: 0.0
diffusion/T:
  desc: null
  value: 3
optimizer_X/lr:
  desc: null
  value: 0.001
optimizer_X/weight_decay:
  desc: null
  value: 0.0
optimizer_X/amsgrad:
  desc: null
  value: true
optimizer_E/lr:
  desc: null
  value: 0.0003
optimizer_E/weight_decay:
  desc: null
  value: 0.0
optimizer_E/amsgrad:
  desc: null
  value: true
lr_scheduler/factor:
  desc: null
  value: 0.9
lr_scheduler/patience:
  desc: null
  value: 5
lr_scheduler/verbose:
  desc: null
  value: true
train/num_epochs:
  desc: null
  value: 10000
train/val_every_epochs:
  desc: null
  value: 1
train/patient_epochs:
  desc: null
  value: 20
train/max_grad_norm:
  desc: null
  value: 10.0
train/batch_size:
  desc: null
  value: 16384
train/val_batch_size:
  desc: null
  value: 131072
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1714825810.975809
    t:
      1:
      - 1
      - 5
      - 52
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 52
      - 53
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.9.19
      5: 0.15.4
      8:
      - 2
      - 5
