defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : cora
    - denoiser : denoiser_default

hydra:
  job:
    chdir: True
  run:
    dir: .




