conf:
  save: True
  save_dir: rand_results

hparams:
  dataset_path: data/
  fixed_random_seeds_path: data/seeds.pt
  device: 'cuda'
  num_seeds: 5

  datatype: "graphs"
  protected: True

  lr: 0.001
  weight_decay: 0.0005
  max_epochs: 1_000
  early_stopping: 50
  logging: False

  alpha: 0.01
  pre_n_samples: 100
  n_samples: 10000   

  smoothing_config:
    smoothing_distribution: "hierarchical_sparse"
    append_indicator: False
    p: 0.8
    p_plus: 0.01
    p_minus: 0.65
  
  dataset: "cora"
  in_channels: 1433 
  out_channels: 7

  arch: "GCN"
  k_heads: 8
  k_hops: 8
  appnp_alpha: 0.15
  hidden_channels: 16
  with_skip: False
